Fix DeprecationWarning: pkg_resources is deprecated as an API
pymorphy2-fork/pymorphy2 pull request #19
Opened 2023-11-15 15:27 UTC by valentino-sm

2023-11-15 18:09 UTC, insolor commented
@valentino-sm I've dropped Python < 3.8 already, so code can be simplified

2023-11-15 21:14 UTC, insolor requested changes

2023-11-15 21:14 UTC, insolor commented on pymorphy2/analyzer.py
> +    return list(result)
It's not necessary to convert the result into a list. The result is used as an iterable object in a for loop (in `_lang_dict_paths` function below). So, `set` is quite suitable.

2023-11-15 23:19 UTC, valentino-sm commented on pymorphy2/analyzer.py
> -    """ Like pkg_resources.iter_entry_points, but uses a WorkingSet which
Could you tell me the correct docstring, that should be good.

Thank you for your support and maintain the project❤️

2023-11-16 07:51 UTC, insolor commented on pymorphy2/analyzer.py
> +            result.update(ep.get(group) or ())
`ep.get(group) or ()` can be changed to `ep.get(group, ())`

2023-11-16 07:59 UTC, insolor commented on pymorphy2/analyzer.py
> -    """ Like pkg_resources.iter_entry_points, but uses a WorkingSet which
Something like that:
```
"""
Finds entry points of installed packages, including ones installed
after the current process is started.

The main use case is to make ``!pip install pymorphy2-fork`` work
within a Jupyter or Google Colab notebook.
See https://github.com/kmike/pymorphy2/issues/131
"""
```

2023-11-16 17:05 UTC, valentino-sm commented on pymorphy2/analyzer.py
> +            result.update(ep.get(group) or ())
Of course you are right, this is only for strict type checking with a return value of `Entrypoints | None`

2023-11-16 17:18 UTC, merged

2023-11-16 17:18 UTC, insolor commented
Thank you for the contribution 👍🏻

2023-12-30 09:25 UTC, BLKSerene commented
@valentino-sm Hi, would you mind if I port this PR to https://github.com/no-plagiarism/pymorphy3?

2023-12-30 18:51 UTC, valentino-sm commented
> @valentino-sm Hi, would you mind if I port this PR to https://github.com/no-plagiarism/pymorphy3?

Sure!
Thank you everyone for your work